# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "PM1: Semantics w/ Pictures"
email: david.schlangen@uni-potsdam.de
description: >- # this means to ignore newlines until "baseurl:"
  Course website for PM1: Semantics with Pictures, Summer 2019
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

search_enabled: true

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

plugins:
#  - jekyll-feed

aux_links:
  "All Classes":
  - "//github.com/compling-potsdam"

permalink: pretty

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

